### ISSUE TITLE
打印不工作

### ISSUE THREAD

**Issue by allen12921** [NewFuture/WebPrint#1]
windows 10设置了默认打印机（可以直接在系统中打印成功），安装了IIS,ASP，通过web页面添加了文件，file目录中已经可以看到上传的文件，但实际并未打印。
不知到是哪里出问题了，是否有日志可以查看呢？

**Comment by NewFuture** [comment]
两种比较大的可能性：
1.  IIS无用户权限,这个时候会报错
2.  SumatraPDF打印出错 bin里面有打印日志

**Comment by allen12921** [comment]
多谢回答。我在SumatraPDF.exe目录并未找到错误日志，但是手动以去运行这个exe文件时候，提示不支持64位的操作系统。。我的系统是win 10 64位，不知道是不是这个程序不能支持呢？

**Comment by NewFuture** [comment]
https://www.sumatrapdfreader.org/download-free-pdf-viewer.html
下载其他版本的试试
> Portable version: | SumatraPDF-***.zip

我测试的32位能在64位机器上运行，你可以试试下载64位版本解压替换掉

**Comment by allen12921** [comment]
换了最新的版本可以运行，我上传的是txt文件，还是没打印，是不是只能打印SumatraPDF支持的文件格式呢？他所支持的文件类型里面好像没有txt和doc呢

**Comment by NewFuture** [comment]
pdf和图片可以正常打印?

txt和word调用的是写字板 ：<kbd>win</kbd>+<kbd>R</kbd> 输入 `write` 看看能调出来不？

**Comment by allen12921** [comment]
重启电脑后发现可以正常打印了。。谢谢帮助
