### ISSUE TITLE
[bug] 写字板读取.doc乱码及其解决

### ISSUE THREAD

**Issue by northword** [NewFuture/WebPrint#4]
写字板打开.doc文档是乱码，1页的文档可以打出44页乱码😂

或许应该默认屏蔽.doc文件上传，如果用户需要doc文件支持，可以自行下载libreoffice或ms office，然后自行加入命令。

我这儿有一份改好的，但是因为改了页脚版权部份，所以还没有提起pr

https://github.com/Northword/WebPrint

https://github.com/northword/WebPrint/blob/dev/Default.aspx.cs#L220

另外，在我的机器上，SumatraPDF 在指定appdata后无法成功打印，只是启动了一个进程，打印机没有任务，所以如果有类似问题的可以考虑删除appdata参数。

**Comment by NewFuture** [comment]
word确实可能有排版兼容问题，特别是有字体和复杂排版的。
但是直接去掉不太妥当，毕竟这里已经提示了word可能有问题。

至于第二个方案，这个版本不太通用的。
可以自动检测 机器上是否安装了 office/wps/libreoffice 调用对应的打印最后是用写字板调用打印。
(尽可能少的让用户去配置和设置)
